### ISSUE TITLE
Add filter or setting to disable create_purchase API event

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/convertkit-paid-memberships-pro#24]
**Is your feature request related to a problem? Please describe.**
Separate API calls at membership checkout can slow down a checkout experience. If people aren't using / don't need the [purchase info in ConvertKit](https://help.convertkit.com/en/articles/2502675-purchases-feature-setup-and-faq), let's create a filter and setting to remove that call.

**Describe the solution you'd like**
Add a filter and potentially a new setting to disable sending purchase data to ConvertKit.

**Comment by dparker1005** [comment]
This will be in v1.2.1
