### ISSUE TITLE
Use First and Last Name values in the first_name and last_name CK fields

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/convertkit-paid-memberships-pro#28]
**Is your feature request related to a problem? Please describe.**
We currently set the username as the first_name when subscribing a member (https://github.com/strangerstudios/convertkit-paid-memberships-pro/blob/dev/includes/class-convertkit-pmp-api.php#L126)

There are cases where a member's username is their first and last name which looks out of place once saved

**Describe the solution you'd like**
Check if the first and last name fields are present, save them in their respective tags, or fall back to the username value

**Describe alternatives you've considered**
We don't have any filters around the subscribe or update code to do this with a code recipe

**Comment by kimcoleman** [comment]
Looking at this more, we rather set the $user_name to first last here: https://github.com/strangerstudios/convertkit-paid-memberships-pro/blob/dev/admin/class-convertkit-pmp-admin.php#L522

We should probably update this to use first_name if set otherwise fall back to display_name.

I'll do a PR.
