### ISSUE TITLE
Refactor error logging / debug in this plugin

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/convertkit-paid-memberships-pro#8]
**Describe the bug**
Right now, this plugin is supposed to be saving debug/log information to the log.txt file in the plugin folder if you've enabled the constant to log things. I'm not having success with this.

**To Reproduce**
1. Add `define( 'CK_DEBUG', true );` to your wp-config.php file.
2. Add a new user and tag them, triggering the add_tag_to_subscriber API call.
3. Check your log.txt in the plugin folder.
4. No information is logged.

We should consider overhauling this to use a system similar to PMPro core and just save logs to the WordPress default debug.log file. Or fix the log.txt in this plugin method to work.

**Comment by JarrydLong** [comment]
I wasn't able to replicate this but found that the log file is generated in \plugins\convertkit-paid-memberhips-pro\includes/log.txt instead of a logs file like we do in core. I've added a filter in the PR to allow devs to change the path though.
